### ISSUE TITLE
Angular or Vue

### ISSUE THREAD

**Issue by wodka** [ohmyform/ohmyform#16]
#### What's this issue about?
right now ohmyform runs on angularjs (1.7.8)

Since an upgrade to angular (2 and up) will require a rewrite perhaps switch to another platform that is easier to extend.

Features I'd like to see then:

* modern development stack with typescript (less bugs)
* more components (there should not be the mixing of files as it is right now)
* get rid of hashbangs -> each path should be rendered and therefor be seo friendly
* reduce dependencies of various libraries
* expose api on clean endpoints and provide redoc / swagger for api access
* add proper api key handling

my personal preference is to switch to [VueJS](https://vuejs.org) (with [NuxtJS](https://nuxtjs.org) to handle the frontend - and [NestJS](https://nestjs.com) to provide the API)

**Comment by wodka** [comment]
any objections?

**Comment by Leopere** [comment]
As per usual sounds reasonable in my mind, I think since we're still technically pre-1.0 it should be acceptable to make major changes as such.  If anything I would recommend that we stick with anything that meets a happy medium between developer friendliness, repeatability, and usability.

If the codebase is hard to find people to code for it then it's less good for longterm maintenance.  If an update to VueJS/NuxtJS/NestJS that would be fine to me.

**Comment by wodka** [comment]
The problem with the current codebase is that it was built for angularjs (1.x) - and to get it to 2.x a rewrite is required - it is still called angular but does not have many things in common.

Keeping this in mind means that even just "upgrading" to a more current version will change everything...

my take on VueJS with NuxtJS is that I'm using it all the time and I just see a bigger and bigger community working with it because it's easy to work with :)

**Comment by Leopere** [comment]
@wodka as long as we don't see regressions I think it's likely a good idea.  Refactoring is fine but if we can't make it modern without huge feature regressions it might be more bad than good.

**Comment by r-t-k** [comment]
I am all about going Vue with Nuxt for 2.x. @wodka @Leopere
